services:
  - type: web
    name: crm-lentini-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.mpnsjgjpiujexmwtndlm:CrmLentini2024!Secure@aws-0-eu-west-1.pooler.supabase.com:6543/postgres
      - key: FRONTEND_URL
        value: https://crm-lentini.netlify.app
